apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-app
  labels:
    app: projeto-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: projeto-app

  template:

    metadata:
      labels:
        app: projeto-app

    spec:
      containers:
      - name: projeto-app
        image: alan2442/projeto4:60236fd441b0af4328f7e521f79b568ebb8aad55
        imagePullPolicy: Always       # garante que Kubernetes baixe a nova imagem
        ports:
          - containerPort: 8080




