apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-app
  labels:
    app: projeto-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: projeto-app

  template:

    metadata:
      labels:
        app: projeto-app

    spec:
      containers:
      - name: projeto-app
        image: alan2442/projeto4:5f35f383d61ad9d7f9cf797f1b54ce68ba4d9bb2
        imagePullPolicy: Always       # garante que Kubernetes baixe a nova imagem
        ports:
          - containerPort: 8080




